### ISSUE TITLE
Generating docs fails due to pkgdown problems

### ISSUE THREAD

**Issue by jeroen** [ropensci/virtuoso#30]
The pkgdown for this package still fails because it depends on a package `rdftools` which is neither on cran nor in ropensci.

We can install it from Github, but then it fails like so:

```
Reading 'vignettes/articles/datalake.Rmd'
Error : callr subprocess failed: Virtuoso installation not detected. Try running: vos_install()
Error: callr subprocess failed: callr subprocess failed: Virtuoso installation not detected. Try running: vos_install()
```

See build log: https://dev.ropensci.org/job/virtuoso/lastBuild/console

Any hints how to get this fixed?

**Comment by cboettig** [comment]
Thanks @jeroen , and sorry for the trouble.  On Linux this package also requires `virtuoso-opensource` be installed (e.g. via `apt-get`, not sure what it's called on rpm systems).  I didn't add that in SysRequirements section since I was worried that would be confusing to Mac /Windows folks where this isn't needed, but maybe I should have?

**Comment by jeroen** [comment]
We can add it to the docs image.

**Comment by jeroen** [comment]
Installed virtuoso-opensource on the server, now it's failing like this:

```
Writing 'articles/index.html'
Reading 'vignettes/articles/datalake.Rmd'
Error : callr subprocess failed: Error importing: airlines.nq 37000 SP029: NQuads RDF loader, line 2: syntax errorError importing: flights.nq 37000 SP029: NQuads RDF loader, line 2: syntax errorError importing: planes.nq 37000 SP029: NQuads RDF loader, line 2: syntax error
Error: callr subprocess failed: callr subprocess failed: Error importing: airlines.nq 37000 SP029: NQuads RDF loader, line 2: syntax errorError importing: flights.nq 37000 SP029: NQuads RDF loader, line 2: syntax errorError importing: planes.nq 37000 SP029: NQuads RDF loader, line 2: syntax error
```

**Comment by cboettig** [comment]
thanks, this vignette is precomputed now.

**Comment by jeroen** [comment]
Awesome, can you please add https://docs.ropensci.org/virtuoso/ to the URL field in the package DESCRIPTION?

**Comment by cboettig** [comment]
done.
