### ISSUE TITLE
Unable to run vos_start()

### ISSUE THREAD

**Issue by lddurbin** [ropensci/virtuoso#32]
I've been using this package weekly for months with no problems, but now it throws an error when I try to run vos_start():

```
Error in Sys.getenv("VIRTUOSO_DB", virtuoso_app$data()) : 
  attempt to apply non-function
```
I'm on a Mac, and I've updated all of my packages, and R, and R Studio.

This is my first time submitting an issue on Github, so let me know what additional information I should provide. Thank you for your help.

**Comment by cboettig** [comment]
Thanks for reporting, this looks like an issue with a recent version of rappdirs.  

Can you test my patch and see if it fixes things? Do:

```r
remotes::install_github("ropensci/virtuoso@patch/rappdirs")
```

clear your workspace, restart R, and try again?  Thanks!

**Comment by lddurbin** [comment]
Yes, that has fixed the issue. Thank you!
