### ISSUE TITLE
vignette failure

### ISSUE THREAD

**Issue by maelle** [ropensci/virtuoso#40]
We see https://github.com/r-universe/ropensci/runs/6608959186?check_suite_focus=true via https://ropensci.r-universe.dev/ui#builds

Should the vignette be prebuilt? https://ropensci.org/blog/2019/12/08/precompute-vignettes/

**Comment by cboettig** [comment]
Long-running vignettes are already pre-built.  Not sure why that vignette is failing, that is more minimal, and runs much the same code as is in the test suite.

**Comment by jeroen** [comment]
This packages has articles under a subdir [vignettes/articles](https://github.com/ropensci/virtuoso/tree/master/vignettes/articles) which R does not include as vignettes. 

One of the articles is precomputed but the other is not (and fails).

**Comment by maelle** [comment]
right but the tests do not fail and they use the same code

**Comment by jeroen** [comment]
I think the tests don't run either because they are all `skip_on_cran` and we mimic CRAN (we don't set CI or NOT_CRAN)

**Comment by maelle** [comment]
Ok then maybe better to pre-build this vignette too?

**Comment by jeroen** [comment]
Yeah I don't know what is going on, was it working before? From the build logs it seems that the required ubuntu package is getting installed? Should it maybe start some sort of service?

**Comment by maelle** [comment]
@cboettig do you know whether this was working before?

**Comment by cboettig** [comment]
As it notes in https://github.com/ropensci/virtuoso/blob/master/vignettes/articles/virtuoso.Rmd#L38, on a linux system virtuoso database server needs to be installed on the os, e.g. via apt, for that to work.  On Mac (and windows I think, though I believe the windows installer always requires user interactive confirmation?) the system should handle the auto-installation first.  

I can convert this into a pre-built vignette when I have a chance; I agree it doesn't need to be re-built regularly, but then I'd thought that the convention was that things in subfolders of `vignettes/` didn't get built by CRAN right? so this is just for pkgdown site?

**Comment by maelle** [comment]
Yes it is a pkgdown build failure indeed.

**Comment by maelle** [comment]
@cboettig kind reminder to pre-build the vignette :smile_cat:

**Comment by maelle** [comment]
@cboettig kind reminder  :smile_cat:

**Comment by cboettig** [comment]
ha sorry, finally did this (with ye old pre-knitted Rmd trick).

This should work on debian linux if the package `virtuoso-opensource` is installed on the universe machine though I think.  Is there a good way to do this (cc @jeroen ?)  (I didn't list it in DESCRIPTION since it's technically not an install time dependency...)

**Comment by cboettig** [comment]
https://github.com/ropensci/virtuoso/commit/200c4b984ed3f4158ccc161c8ad2c686dc10eb24

**Comment by maelle** [comment]
:tada: Thanks so much
